[project]
name = "typeguard-conditional-import"
version = "0.1.0"
description = "Conditionally import typeguard sample code"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rich>=13.9.4",
    "typeguard>=4.4.2",
]
